apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    name: webapp-color
spec:
  containers:
    - env:
      - name: APP_COLOR
        value: green
      image: kodekloud/webapp-color
      name: webapp-color